## Provides access to all m12NameGenerator tags as constants. Updates every ~5s. Edit frequency of update in m12_name_generator.gd
class_name m12NameGeneratorAutoTags
const M_12_DESCRIPTORS = "m12_descriptors"
const ADJECTIVES = "adjectives"
const COLOR = "color"
const COMMON_COLORS = "common_colors"
const UNUSUAL_COLORS = "unusual_colors"
const X_11_COLORS = "x11_colors"
const M_12_ENGLISH = "m12_english"
const ARCHAIC_FEMALE = "archaic_female"
const ARCHAIC_MALE = "archaic_male"
const FEMALE = "female"
const MALE = "male"
const WESTERN = "western"
const CONTEMPORARY = "contemporary"
const AMERICAN = "american"
const M_12_FRENCH = "m12_french"
const ARCHAIC = "archaic"
const M_12_ORDINAL_NUMBERS = "m12_ordinal_numbers"
const NUMERIC_IDENTIFIERS = "numeric_identifiers"
const ORDINAL_ENGLISH_TEXT = "ordinal_english_text"
const ORDINAL_IDENTIFIERS = "ordinal_identifiers"
